disabled_rules:
    - force_cast
    - trailing_whitespace

opt_in_rules:
    - array_init
    - closure_spacing
    - closure_body_length
    - collection_alignment
    - contains_over_filter_is_empty
    - contains_over_filter_count
    - contains_over_first_not_nil
    - discouraged_object_literal
    - duplicate_enum_cases
    - empty_count
    - empty_string
    - empty_xctest_method
    - explicit_init
    - extension_access_modifier
    - fatal_error_message
    - file_name_no_space
    - first_where
    - flatmap_over_map_reduce
    - implicit_return
    - joined_default_parameter
    - last_where
    - let_var_whitespace
    - literal_expression_end_indentation
    - modifier_order
    - multiline_function_chains
    - operator_usage_whitespace
    - overridden_super_call
    - private_action # Keeps your UI code closed within the implementation class and it avoids leaking UIKit to higher layers.
    - private_outlet # Keeps your UI code closed within the implementation class and it avoids leaking UIKit to higher layers.
    - prohibited_super_call
    - quick_discouraged_call
    - redundant_optional_initialization
    - required_enum_case
    - sorted_imports
    - switch_case_on_newline
    - todo
    - toggle_bool
    - unowned_variable_capture
    - unused_capture_list
    - unused_declaration
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - comment_spacing

included: # paths to include during linting. `--path` is ignored if present.
    - ./

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods

# These properties are marked as error by default.
force_try: warning

closure_body_length:
    warning: 30
    error: 40

file_length:
    warning: 540
    error: 550

function_body_length:
    warning: 100
    error: 150

type_body_length:
    warning: 340
    error: 360

function_parameter_count:
    warning: 10
    error: 15

line_length:
    warning: 155
    error: 160
    ignores_comments: true
    ignores_urls: true

type_name:
    min_length: 4
    max_length:
        warning: 55
        error: 60
    allowed_symbols: ["_"]

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

custom_rules:
    double_space: # From https://github.com/IBM-Swift/Package-Builder
        include: "*.swift"
        name: "Double space"
        regex: "([a-z,A-Z] \\s+)"
        message: "Double space between keywords"
        match_kinds: keyword
        severity: warning
    
    mark_newline:
        include: "*.swift"
        name: "MARK new line"
        regex: "(^ *\\/\\/ MARK:\ [ a-zA-Z0-9=?.\\(\\)\\{\\}:,><!-]*\n *(?!(?:\\}|return))\\S+)"
        message: "// MARK: should have new line after"
        severity: warning
    
    empty_line_after_super:
        name: "Empty Line After Super"
        regex: "(^ *super\\.[ a-zA-Z0-9=?.\\(\\)\\{\\}:,><!]*\n *(?!(?:\\}|return))\\S+)"
        message: "There should be an empty line after super"
        severity: warning
    
    new_line_between_import:
        name: "New line between import"
        regex: "import(.*?)\n\n+import"
        message: "No new line between import"
        severity: warning
